apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-preprocessor
  labels:
    app: document-preprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-preprocessor
  template:
    metadata:
      labels:
        app: document-preprocessor
    spec:
      containers:
        - name: document-preprocessor
          image: document-preprocessor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: document-preprocessor-service
spec:
  selector:
    app: document-preprocessor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
