apiVersion: v1
kind: Service
metadata:
  name: requirement-service
spec:
  type: ClusterIP
  selector:
    app: requirement-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
