version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: testcase_postgres
    restart: always
    environment:
      POSTGRES_DB: testcase_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-service:
    build: .
    container_name: testcase-db-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: testcase_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"

volumes:
  postgres_data:
